[package]
name = "raytracing-in-a-weekend-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.11"
rand = "0.9.1"
rng = "0.1.0"

[lib]
name = "raytracing_in_a_weekend_rust"
path = "src/lib.rs"
